name: Build and Publish to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.17'

      - name: Install pnpm & jq
        run: |
          npm install -g pnpm
          sudo apt-get install jq

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm cf:build

      - name: Deploy to Production Environment
        run: pnpm cf:github:publish -- --branch=${{ github.ref }} --commit-hash=${{ github.sha }} --commit-message="${{ github.event.head_commit.message }}"
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
